# Generated by Django 3.2.12 on 2022-08-22 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='creators_project',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='creator',
            new_name='creator_keep',
        ),
    ]
