# Generated by Django 3.2.12 on 2022-09-18 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODO', '0006_alter_project_creators_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creator_keep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Пользователь, создавший заметку'),
        ),
    ]
